spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demodb}
    username: ${DB_USER:demo_user}
    password: ${DB_PASSWORD:demo_user}
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
    properties:
      hibernate.default_schema: demo
  application:
    name: report-demo
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  tomcat:
    max-threads: 200
